# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "The Madison Reunion"
email: "ben@madisonreunion.com"
description: "Bringing the '60s back home"
baseurl: ""
url: "http://madisonreunion.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-"
#googleAnalyticsSiteUrl: "gdg-x.github.io"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "The Madison Reunion"
organizerAlternateName: "The Madison Reunion"
organizerDescription: "Bringing the '60s back home"
organizerEmail: "ben@madisonreunion.com"
organizerLogo: "/img/logo/bucky-logo-black-w-text.png"
organizerLink: "http://madisonreunion.com"

# Head
#metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
#twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
# c4pUrl: "https://bit.ly/dfua-c4p"
# c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/#top-section-hero", text: "Home"}
 #- {permalink: "/blog/", text: "Blog"}
 - {permalink: "/#about", text: "About"}
 - {permalink: "/#latest-news", text: "Panels"}
 - {permalink: "/#rockstar-speakers", text: "Speakers"}
 - {permalink: "/#subscribe", text: "Register"}
 #- {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 #- {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
 #- {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "union-chairs-header.jpg"
heroTitle: "A Party With a Purpose <typeout>"
eventDate: "June 14 - 17 2018"
typeoutTextValues: '"1960", "2018"'
typeoutFallback: "2018"
heroButtons:
 #- {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Register Here"}

# About Block
aboutTitle: "About The Madison Reunion"
aboutBlock:
 - {title: "The Madison Reunion", image: "about-bucky-logo-black-w-text.png", text: "The city was ground zero for the civil rights, anti-war and social justice movements during the ‘60s and students at the University of Wisconsin benefitted from the teachings of brilliant historians who encouraged them to put the Wisconsin Idea into practice.<br/><br/>The Madison Reunion will bring these former students and faculty back to celebrate and re-examine the experience they had in Madison during the turbulent ‘60s.", permalink: "/reunion/", btn-text: "Reunion information" }
 - {title: "Conference on Madison in the ‘60s", image: "about-conference-logo-128h.png", text: "While The Madison Reunion expects many to return to Madison to enjoy the weather and relive their salad days, with many free, fun activities planned, the Conference on Madison in the ‘60s is expected to draw some 1,000 attendees. Held at the Memorial Union, for a modest fee, registrants will enjoy three days of panels, seminars, and interviews on the cultural movements and personal experiences of that radical decade.", permalink: "/schedule/", btn-text: "Conference Schedule" }
 #- {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "rosebowl-float.jpg"
statisticBlock:
 #- {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 #- {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 #- {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 #- {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Panels We Are Currently Planning"

# Rockstar Speakers Block
rockstarSpeakersImage: "indoor_rally.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Planned Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Downtown Madison"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "1308 W Dayton St"
eventAddressLocality: "Madison"
eventAddressLocalityRegion: "Wisconsin"
eventPostalCode: "53715"
eventAddressCountry: "USA"
eventStartTime: "2018-06-14T09:00"
eventDoorTime: "09:00"
eventEndTime: "2018-06-20T20:00"
eventPlaceCoordinates: "43.0719167, -89.4103726"
mapCenterCoordinates: "43.0719167, -89.4103726"
mapMobileCenterCoordinates: "43.0717916, -89.4100213"

# Venue Block
venueBlockTitle: "Madison In The '60s"
venueBigImage: "street-night.jpg"
venueSmallImage1: "state-st-1960.jpg"
venueSmallImage2: "register-sombrero.jpg"
venueSmallImage3: "pharm-counter.jpg"
venueTitle: "Downtown Madison"
venueFeatures: ["Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "MadisonWisconsin1960s_700.jpg"
#tweetsFeedTitle: "What's Up?"
#twitterHashTag: "devfest"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: ""
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Register"
#subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 # - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 # - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
 - {link: "https://facebook.com/madisonreunion", icon: "facebook"}
 #- {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
  #  - {link: "http://gdg.org.ua", text: "GDG.org.ua"}
  #  - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "ben@madisonreunion.com", text: "ben@madisonreunion.com"}
 -
  title: "FAQ"
  links:
   #- {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
#discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "The Madison Reunion"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Free Madison Reunion Activities"
hackathonRows:
 - {title: "Welcome:", image: "about-conference-in-60s-logo.png", details: "In Alumni Park with Mayor Soglin"}
 - {title: "Keynote:", image: "about-conference-in-60s-logo.png", details: "TBA"}
 - {title: "Blues for Madison:", image: "about-conference-in-60s-logo.png", details: "Concert with Boz Scaggs, Tracy Nelson, Ben Sidran et. al."}
 - {title: "Tours:", image: "about-conference-in-60s-logo.png", details: "Campus Tours
<ul>
<li> Mifflin St. Historic Tour</li>

<li>Ride the Trolley down State St. and around The Square</li>

<li>Where You Went Wrong find where you used to live and what it is now</li>

<li>Food Tour The Plaza, The Brat House, The Nitty Gritty and you won’t believe what else</li>

<li>Frank Lloyd Wright’s Monona Terrace and the Otis Redding Memorial Park</li>

<li>The Lake Path and Picnic Point</li>

<li>Babcock Hall Ice Cream Social on the Union Terrace</li>
</ul>"}
 - {title: "Music:", image: "about-conference-in-60s-logo.png", details: "Daily jam sessions in the Rathskeller, nightly concerts on the Terrace and Rockin’ John’s dance party in Great Hall"}
 - {title: "Films:", image: "about-conference-in-60s-logo.png", details: "Sponsored by the UW Cinematique; The War at Home and ‘60s classics like Easy Rider, Butch Cassidy &amp; The Sundance Kid, Bonnie and Clyde and The Graduate"}
 - {title: "Photography:", image: "about-conference-in-60s-logo.png", details: "Exhibits in the Union Gallery and State Historical Society"}
 - {title: "Electronic Bulletin Board:", image: "about-conference-in-60s-logo.png", details: "Find friends, leave messages"}
 - {title: "The Memory Booth:", image: "about-conference-in-60s-logo.png", details: "Record your most vivid recollection of the times"}
 - {title: "Souvenirs:", image: "about-conference-in-60s-logo.png", details: "T-shirts, Tote Bags, Hats, Mugs, more..."}
 - {title: "Housing:", image: "hackathon-2.png", details: "Relive your life in the dorms or find a hotel close by, we’ll help"}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
